name: Build Apache HTTPD Stack (MSYS2 UCRT64 + VS17)

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: CMake build type
        type: choice
        required: true
        default: Release
        options: [Release, Debug]
      platform:
        description: Target architecture
        type: choice
        required: true
        default: x64
        options: [x64]  # MSYS2 UCRT64 в этом примере только x64

env:
  BUILD_BASE: C:\Development\Apache24\build
  PREFIX: C:\Apache24
  INSTALL_PDB: OFF

jobs:
  build:
    name: Build Apache with MSYS2 UCRT64 + VS17
    runs-on: windows-2022
    timeout-minutes: 360

    env:
      PLATFORM: ${{ inputs.platform }}
      BUILD_TYPE: ${{ inputs.build_type }}
      BUILD_BASE: C:\Development\Apache24\build
      PREFIX: C:\Apache24
      INSTALL_PDB: OFF

    outputs:
      platform: ${{ steps.outvars.outputs.platform }}
      build_type: ${{ steps.outvars.outputs.build_type }}
      artifact_name: ${{ steps.outvars.outputs.artifact_name }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure PLATFORM/BUILD_TYPE defaults
        id: ensure-defaults
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          if (-not $env:PLATFORM -or $env:PLATFORM -eq '') { "PLATFORM=x64" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8 }
          if (-not $env:BUILD_TYPE -or $env:BUILD_TYPE -eq '') { "BUILD_TYPE=Release" | Out-File -FilePath $env:GITHUB_ENV -Append -Encoding utf8 }
          "Using PLATFORM=$env:PLATFORM, BUILD_TYPE=$env:BUILD_TYPE"

      - name: Enable long paths (Windows)
        shell: pwsh
        run: git config --system core.longpaths true

      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            base-devel
            git
            tar
            gzip
            xz
            unzip
            perl
            nasm
            zip
            p7zip  # 7z в MSYS2
          path-type: minimal

      - name: Show MSYS2 env
        shell: msys2 {0}
        run: |
          uname -a
          which bash
          which tar
          which perl
          which 7z || true
          echo MSYSTEM=$MSYSTEM

      - name: Install CMake (system) and 7zip (Windows)
        shell: pwsh
        run: |
          choco feature enable -n allowGlobalConfirmation
          choco install cmake --installargs "ADD_CMAKE_TO_PATH=System" --no-progress --yes
          choco install 7zip --no-progress --yes
          cmake --version

      - name: Setup MSVC 2022 (VS17, toolset v143)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ env.PLATFORM }}

      - name: Show MSVC
        shell: cmd
        run: |
          echo Using VS17 toolset v143
          where cl
          where nmake

      - name: Run build script under MSYS2 bash (using MSVC toolchain)
        shell: msys2 {0}
        env:
          PLATFORM: ${{ env.PLATFORM }}
          BUILD_TYPE: ${{ env.BUILD_TYPE }}
          BUILD_BASE: ${{ env.BUILD_BASE }}
          PREFIX: ${{ env.PREFIX }}
          INSTALL_PDB: ${{ env.INSTALL_PDB }}
        run: |
          echo "MSYSTEM=$MSYSTEM"
          echo "PATH=$PATH"
          # Добавим Windows tools в PATH (чтобы cmake/nmake/cl были видны внутри MSYS2 env)
          winpath() { powershell.exe -NoLogo -NoProfile -Command '[System.Environment]::GetEnvironmentVariable("PATH","Machine")'; }
          export PATH="/c/Windows/System32:/c/Windows:${PATH}:$(winpath | tr ';' ':' | sed 's#\\#/#g')"

          # Проверим инструменты
          cmd.exe /c "where cl"
          cmd.exe /c "where nmake"
          cmd.exe /c "cmake --version"

          # Запустим .bat напрямую через cmd, чтобы он остался совместим
          cmd.exe /c ^
            "set PLATFORM=%PLATFORM% && set BUILD_TYPE=%BUILD_TYPE% && set BUILD_BASE=%BUILD_BASE% && set PREFIX=%PREFIX% && set INSTALL_PDB=%INSTALL_PDB% && call build_all.bat"

      - name: Prepare outputs
        id: outvars
        if: always()
        shell: pwsh
        run: |
          $artifact = "Apache24-$env:PLATFORM-$env:BUILD_TYPE"
          "platform=$env:PLATFORM" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "build_type=$env:BUILD_TYPE" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8
          "artifact_name=$artifact" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

      - name: Upload build prefix
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.outvars.outputs.artifact_name }}
          path: C:\Apache24\**
          if-no-files-found: warn
          compression-level: 6
          retention-days: 14

      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-${{ steps.outvars.outputs.platform }}-${{ steps.outvars.outputs.build_type }}
          path: |
            C:\Development\Apache24\build\**\CMakeFiles\CMakeOutput.log
            C:\Development\Apache24\build\**\CMakeFiles\CMakeError.log
            C:\Development\Apache24\build\**\*.log
          if-no-files-found: ignore

  release:
    name: Draft GitHub Release
    needs: build
    if: github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' || github.event_name == 'push')
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: dist

      - name: Create release archive
        shell: pwsh
        run: |
          $ErrorActionPreference = 'Stop'
          $zip = "Apache24-${{ needs.build.outputs.platform }}-${{ needs.build.outputs.build_type }}-${{ github.run_number }}.zip"
          if (Test-Path "dist") {
            if (Test-Path $zip) { Remove-Item $zip -Force }
            Compress-Archive -Path "dist\*" -DestinationPath $zip -CompressionLevel Optimal
            Write-Host "Zipped: $zip"
          } else {
            Write-Host "dist folder not found; skipping."
          }

      - name: Create GitHub Release (draft)
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          tag_name: build-${{ github.run_number }}
          name: "Apache24 Build #${{ github.run_number }}"
          body: |
            Automated build for commit ${{ github.sha }}.
            Platform: ${{ needs.build.outputs.platform }}
            Build Type: ${{ needs.build.outputs.build_type }}
          files: |
            Apache24-*.zip